apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: bjp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      version: v1
  template:
    metadata:
      labels:
        app: web
        version: v1
    spec:
      containers:
        - name: web
          image: httpd
          ports:
            - containerPort: 80