apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flagger-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: flagger
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s